// SPDX-License-Identifier: MIT
// Copyright (c) 2026 K. S. Ernest (iFire) Lee
//
// content/record-macros.scm + content/combat.scm, concatenated and
// wrapped in a single (begin ...) form (s7_eval_c_string reads and
// evaluates exactly one datum from a string - a bare sequence of
// top-level defines needs this wrapper, the same real bug
// s7_sandbox_guest.c's own header comment documents hitting once
// already), then C-string-escaped for direct #include into a guest
// program that has no filesystem access to load these at runtime. A
// pinned snapshot, not a live mirror - if record-macros.scm or
// combat.scm change, this file is stale until manually regenerated
// (same discipline ADR 0032 already established for every other
// ported .scm file in this repo).
static const char *k_combat_scm =
	"(begin\n"
	"; SPDX-License-Identifier: MIT\n"
	"; Copyright (c) 2026 K. S. Ernest (iFire) Lee\n"
	";\n"
	"; Lisp macros for the immutable-record-update pattern combat.scm and\n"
	"; progression.scm both hand-wrote as verbose vector reconstructions -\n"
	"; per Paul Graham's \"Beating the Averages\" (ADR 0028's own citation),\n"
	"; macros are the other half of Lisp's development-velocity case besides\n"
	"; interactive iteration: bend the language to the problem instead of\n"
	"; writing the same boilerplate by hand at every call site.\n"
	";\n"
	"; define-record generates a constructor and per-field accessors over a\n"
	"; plain vector (no new runtime type, no allocator beyond a vector - a\n"
	"; deliberate console-grade choice, ADR 0029). record-with generates a\n"
	"; positional reconstruction at macro-expansion time (not a runtime\n"
	"; case-dispatch), so a call site only names what's changing, directly\n"
	"; mirroring Lean's `{ s with f := v }` syntax instead of listing every\n"
	"; unchanged field's accessor by hand.\n"
	"\n"
	"(define-macro (define-record name . fields)\n"
	"  (let* ((name-str (symbol->string name))\n"
	"         (mk (string->symbol (string-append \"make-\" name-str))))\n"
	"    (let loop ((fs fields) (i 0) (accessors '()))\n"
	"      (if (null? fs)\n"
	"          `(begin\n"
	"             (define (,mk ,@fields) (vector ,@fields))\n"
	"             ,@(reverse accessors))\n"
	"          (loop (cdr fs) (+ i 1)\n"
	"                (cons `(define (,(string->symbol (string-append name-str \"-\" (symbol->string (car fs)))) r)\n"
	"                         (vector-ref r ,i))\n"
	"                      accessors))))))\n"
	"\n"
	"; (record-with make-state '(tick combo last-attack hp spawn alive) s (hp (- (st-hp s) dmg)))\n"
	"; -> (make-state (vector-ref s 0) (vector-ref s 1) (vector-ref s 2) (- (st-hp s) dmg) (vector-ref s 4) (vector-ref s 5))\n"
	"; Field positions are resolved at macro-expansion time (a literal quoted\n"
	"; field list, matching the same order define-record used to build the\n"
	"; vector) - no runtime dispatch, no vector-copy, no hidden state shared\n"
	"; between macro invocations.\n"
	"(define-macro (record-with ctor quoted-fields r . updates)\n"
	"  (let ((fields (cadr quoted-fields)))\n"
	"    (let loop ((fs fields) (i 0) (args '()))\n"
	"      (if (null? fs)\n"
	"          `(,ctor ,@(reverse args))\n"
	"          (let ((u (assoc (car fs) updates)))\n"
	"            (loop (cdr fs) (+ i 1)\n"
	"                  (cons (if u (cadr u) `(vector-ref ,r ,i)) args)))))))\n"
	"\n"
	"; SPDX-License-Identifier: MIT\n"
	"; Copyright (c) 2026 K. S. Ernest (iFire) Lee\n"
	";\n"
	"; Hand-ported from v-sekai-multiplayer-fabric/combat's\n"
	"; core/CombatCore/Core.lean (translated line-for-line) - the\n"
	"; combo/invulnerability/damage reducer.\n"
	";\n"
	"; Source of truth: v-sekai-multiplayer-fabric/combat is upstream and\n"
	"; authoritative. This file is a pinned, one-time translation, not an\n"
	"; ongoing mirror - ADR 0032. Ported from commit\n"
	"; f9a1964892c6943e120c82bad398646944aaa10e. If that repo's Core.lean\n"
	"; changes, this file is stale until re-ported by hand against the new\n"
	"; commit - nothing here re-checks upstream automatically.\n"
	";\n"
	"; Uses record-macros.scm's define-record/record-with (ADR 0034) instead\n"
	"; of hand-written vector reconstruction - each `{ s with f := v }` site\n"
	"; now names only what changed, matching the Lean source directly instead\n"
	"; of spelling out every unchanged field's accessor by hand. The quoted\n"
	"; field list is repeated at each record-with call site (unavoidable:\n"
	"; define-macro receives unevaluated syntax, so a variable holding the\n"
	"; field list wouldn't be visible at macro-expansion time) - a real,\n"
	"; accepted cost, still smaller than the boilerplate it replaces.\n"
	";\n"
	"; No (load ...) here: the guest runs entirely inside libriscv's\n"
	"; fuel-metered VMCALL sandbox (resume/pause/gas-limit all come from\n"
	"; that boundary, per ADR 0006) - a guest-side (load \"record-macros.scm\")\n"
	"; would need a real filesystem syscall from inside the sandbox, outside\n"
	"; the gas-limited/marshaled call path entirely. record-macros.scm's\n"
	"; content is concatenated on the HOST side instead (same pattern\n"
	"; s7_riscv_*_golden_test.cpp already uses to assemble one big\n"
	"; expression string before the single VMCALL), never loaded by the\n"
	"; guest itself.\n"
	"\n"
	"(define combo-min-gap 6)\n"
	"(define combo-max-gap 18)\n"
	"(define invuln-ticks 30)\n"
	"(define enemy-max-hp 100)\n"
	"\n"
	"(define (damage-of stage)\n"
	"  (cond ((= stage 0) 10)\n"
	"        ((= stage 1) 15)\n"
	"        (else 25)))\n"
	"\n"
	"(define-record state tick combo last-attack hp spawn alive)\n"
	"\n"
	"(define initial-state (make-state 0 0 0 0 0 #f))\n"
	"\n"
	"; CombatCore.resolveSwing\n"
	"(define (resolve-swing s stage)\n"
	"  (cond\n"
	"    ((not (state-alive s))\n"
	"     (list s (list (list 'swing stage))))\n"
	"    ((< (state-tick s) (+ (state-spawn s) invuln-ticks))\n"
	"     (list s (list (list 'swing stage) 'blocked)))\n"
	"    (else\n"
	"     (let ((dmg (damage-of stage)))\n"
	"       (if (<= (state-hp s) dmg)\n"
	"           (list (record-with make-state '(tick combo last-attack hp spawn alive) s (hp 0) (alive #f))\n"
	"                 (list (list 'swing stage) (list 'hit dmg) 'death))\n"
	"           (list (record-with make-state '(tick combo last-attack hp spawn alive) s (hp (- (state-hp s) dmg)))\n"
	"                 (list (list 'swing stage) (list 'hit dmg))))))))\n"
	"\n"
	"; CombatCore.step\n"
	"(define (combat-step s event)\n"
	"  (cond\n"
	"    ((eq? event 'tick)\n"
	"     (let ((s1 (record-with make-state '(tick combo last-attack hp spawn alive) s (tick (+ (state-tick s) 1)))))\n"
	"       (if (and (> (state-combo s1) 0) (> (state-tick s1) (+ (state-last-attack s1) combo-max-gap)))\n"
	"           (list (record-with make-state '(tick combo last-attack hp spawn alive) s1 (combo 0)) (list 'comboDrop))\n"
	"           (list s1 '()))))\n"
	"    ((eq? event 'spawn)\n"
	"     (list (record-with make-state '(tick combo last-attack hp spawn alive) s\n"
	"             (alive #t) (hp enemy-max-hp) (spawn (state-tick s)))\n"
	"           '()))\n"
	"    ((eq? event 'attack)\n"
	"     (if (= (state-combo s) 0)\n"
	"         (resolve-swing (record-with make-state '(tick combo last-attack hp spawn alive) s\n"
	"                          (combo 1) (last-attack (state-tick s)))\n"
	"                        0)\n"
	"         (let ((gap (- (state-tick s) (state-last-attack s))))\n"
	"           (if (and (<= combo-min-gap gap) (<= gap combo-max-gap))\n"
	"               (let* ((stage (state-combo s))\n"
	"                      (next (if (>= stage 2) 0 (+ stage 1))))\n"
	"                 (resolve-swing (record-with make-state '(tick combo last-attack hp spawn alive) s\n"
	"                                  (combo next) (last-attack (state-tick s)))\n"
	"                                stage))\n"
	"               (list (record-with make-state '(tick combo last-attack hp spawn alive) s (combo 0)) (list 'whiff))))))\n"
	"    (else (list s '()))))\n"
	"\n"
	"; CombatCore.replay\n"
	"(define (combat-replay events)\n"
	"  (let loop ((evs events) (acc (list initial-state '())))\n"
	"    (if (null? evs)\n"
	"        acc\n"
	"        (let* ((r (combat-step (car acc) (car evs))))\n"
	"          (loop (cdr evs) (list (car r) (append (cadr acc) (cadr r))))))))\n"
	"\n"
	")";
